/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        earth: {
          bg: 'var(--bg-primary)',
          secondary: 'var(--bg-secondary)',
          surface: 'var(--surface)',
          elevated: 'var(--surface-elevated)',
          primary: 'var(--primary)',
          'primary-hover': 'var(--primary-hover)',
          'primary-soft': 'var(--primary-soft)',
          'primary-light': 'var(--primary-light)',
          accent: 'var(--accent)',
          'accent-hover': 'var(--accent-hover)',
          'accent-soft': 'var(--accent-soft)',
          amber: 'var(--amber)',
          'amber-soft': 'var(--amber-soft)',
          text: 'var(--text-primary)',
          muted: 'var(--text-secondary)',
          subtle: 'var(--text-muted)',
          border: 'var(--border)',
          'border-strong': 'var(--border-strong)',
        },
        forest: {
          50: '#F2ECE9',
          100: '#E2ECE8',
          200: '#B7D5C9',
          300: '#8CBEA8',
          400: '#52B788',
          500: '#40916C',
          600: '#2D6A4F',
          700: '#1B4332',
          800: '#1C3F34',
          900: '#0F2820',
          950: '#0B1D17',
        },
        clay: {
          50: '#FDF3EE',
          100: '#FBE4D8',
          400: '#E07A5F',
          500: '#C85A32',
          600: '#B34E29',
          700: '#8F3818',
        },
        sand: {
          50: '#FBF9F4',
          100: '#F2EEE5',
          200: '#E2DDD4',
          300: '#C8C2B7',
          400: '#9E978C',
          500: '#787166',
        },
      },
    },
  },
  plugins: [],
}
